definitions:
  config:
    /hippo:namespaces/publishing/base:
      jcr:primaryType: hipposysedit:templatetype
      jcr:mixinTypes: ['editor:editable', 'mix:referenceable']
      jcr:uuid: c56d57e6-0258-4981-9b3c-8c98c9468ba3
      /hipposysedit:nodetype:
        jcr:primaryType: hippo:handle
        jcr:mixinTypes: ['mix:referenceable']
        jcr:uuid: c316cde0-359f-4a0d-96bf-f59515c50af6
        /hipposysedit:nodetype:
          jcr:primaryType: hipposysedit:nodetype
          jcr:mixinTypes: ['mix:referenceable', 'hipposysedit:remodel']
          jcr:uuid: 30132022-82dd-4a1b-847a-c1f1ea487b17
          hipposysedit:node: true
          hipposysedit:supertype: ['publishing:basedocument', 'hippostd:relaxed',
            'hippotranslation:translated', 'hippostd:taggable']
          hipposysedit:uri: http://www.publishing.com/publishing/nt/1.0
          /summary:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: publishing:summary
            hipposysedit:primary: false
            hipposysedit:type: Text
            hipposysedit:validators: [required, summary-words-validator, summary-minlength-validator]
          /title:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: publishing:title
            hipposysedit:primary: false
            hipposysedit:type: String
            hipposysedit:validators: [required, title-words-validator, title-minlength-validator]
          /metaDescription:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: publishing:metaDescription
            hipposysedit:primary: false
            hipposysedit:type: Text
            hipposysedit:validators: [required, summary-words-validator, summary-minlength-validator]
          /seoTitle:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: publishing:seoTitle
            hipposysedit:primary: false
            hipposysedit:type: String
            hipposysedit:validators: [required, title-words-validator, title-minlength-validator]
          /authorNotes:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: publishing:authorNotes
            hipposysedit:primary: false
            hipposysedit:type: Html
          /reportingtags:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: true
            hipposysedit:ordered: false
            hipposysedit:path: publishing:reportingtags
            hipposysedit:primary: false
            hipposysedit:type: String
      /hipposysedit:prototypes:
        jcr:primaryType: hipposysedit:prototypeset
        /hipposysedit:prototype:
          jcr:primaryType: publishing:base
          hippostd:holder: holder
          hippostd:state: draft
          hippostdpubwf:createdBy: ''
          hippostdpubwf:lastModifiedBy: ''
          hippotranslation:id: document-type-locale-id
          hippotranslation:locale: document-type-locale
          jcr:mixinTypes: ['mix:referenceable', 'hippostd:taggable']
          publishing:summary: ''
          publishing:title: ''
          jcr:uuid: 9191e0f0-c20a-4fa7-9598-ca7bb21b7210
          hippostdpubwf:lastModificationDate: 2019-09-03T14:51:07.551+01:00
          hippostdpubwf:creationDate: 2019-09-03T14:51:07.552+01:00
          publishing:seoTitle: ''
          publishing:authorNotes: ''
          publishing:metaDescription: ''
          publishing:reportingtags: []
      /editor:templates:
        jcr:primaryType: editor:templateset
        /_default_:
          jcr:primaryType: frontend:plugincluster
          frontend:properties: [mode]
          frontend:references: [wicket.model, model.compareTo, engine, validator.id]
          frontend:services: [wicket.id, validator.id]
          /root:
            jcr:primaryType: frontend:plugin
            item: ${cluster.id}.field
            plugin.class: org.hippoecm.frontend.service.render.ListViewPlugin
          /title:
            jcr:primaryType: frontend:plugin
            caption: Title
            field: title
            hint: "Enter a title for this page.  \r\n\r\nThis will appear at the top\
              \ of the page on the live site and will also be used in any links to\
              \ this page. A title is required for all pages. \r\n\r\nIt must be between\
              \ 3 and 255 characters."
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.field
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
              maxlength: '255'
              size: '50'
          /summary:
            jcr:primaryType: frontend:plugin
            caption: Summary
            field: summary
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.field
            hint: "Enter a summary of this page.  \r\n\r\nThis summary will be used\
              \ in places where this page is listed on the live website, such as a\
              \ category page and in search results. \r\n\r\nIt must be between 3\
              \ and 255 characters."
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
              maxlength: '255'
          /seoTitle:
            jcr:primaryType: frontend:plugin
            caption: SEO title
            field: seoTitle
            hint: "This title will be used by search engines when indexing the content\
              \ to add it to search results. \r\n\r\nIt must be between 3 and 60 characters.\
              \ You can test yours at: https://moz.com/learn/seo/title-tag"
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.field
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
              maxlength: '60'
          /metaDescription:
            jcr:primaryType: frontend:plugin
            caption: Meta description
            field: metaDescription
            hint: "Describe what content this page covers. Search engines will use\
              \ this content when displaying links to the site in the search listings.\
              \ \r\n\r\nThe description must be between 3 and 255 characters."
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.field
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
              maxlength: '255'
          /taggable:
            jcr:primaryType: frontend:plugin
            mixin: hippostd:taggable
            plugin.class: org.hippoecm.frontend.editor.plugins.mixin.MixinLoaderPlugin
            wicket.id: ${cluster.id}.field
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /reportingtags:
            jcr:primaryType: frontend:plugin
            caption: Reporting tags
            field: reportingtags
            multiselect.type: palette
            palette.alloworder: true
            palette.maxrows: '10'
            plugin.class: org.onehippo.forge.selection.frontend.plugin.DynamicMultiSelectPlugin
            selectlist.maxrows: '10'
            valuelist.provider: service.valuelist.default
            wicket.id: ${cluster.id}.field
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
              source: /content/documents/publishing/valuelists/reportingtags
          /authorNotes:
            jcr:primaryType: frontend:plugin
            caption: Author notes
            field: authorNotes
            hint: Enter any notes relevant to this content item.  This will not appear
              on the page itself.
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.field
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
