/content/gallery/socialsecurity:
  jcr:primaryType: hippogallery:stdImageGallery
  jcr:mixinTypes: ['hippo:named', 'mix:versionable']
  hippo:name: Social Security
  hippostd:foldertype:
    - new-publishing-ColumnImage-folder
    - new-publishing-ColumnImageSixteenNine-folder
    - new-publishing-ColumnImageFourThree-folder
    - new-publishing-ColumnImageOneOne-folder
    - new-publishing-ColumnImageTwentyoneNine-folder
  hippostd:gallerytype: [ 'publishing:ColumnImage' ]
