definitions:
  config:
    /hst:hst/hst:hosts/dev-localhost/localhost/hst:root/economic-action-plan:
      .meta:residual-child-node-category: content
      jcr:primaryType: hst:mount
      hst:mountpoint: /hst:publishing/hst:sites/economic-action-plan
      /preview:
        .meta:residual-child-node-category: content
        jcr:primaryType: hst:mount
        hst:alias: eap-staging
        hst:type: preview
        preview-cookie-httponly: 'false'
        preview-cookie-secure: 'false'
    /hst:hst/hst:hosts/lcl/scot/mygov/economicactionplan:
      jcr:primaryType: hst:virtualhost
      /lcl:
        jcr:primaryType: hst:virtualhost
        /hst:root:
          jcr:primaryType: hst:mount
          hst:mountpoint: /hst:publishing/hst:sites/economic-action-plan
          hst:schemeagnostic: true
          publishing:gtm: /content/documents/economic-action-plan/administration/analytics/dev
    /hst:hst/hst:hosts/dev/scot/mygov/economicactionplan:
      jcr:primaryType: hst:virtualhost
      /dev:
        jcr:primaryType: hst:virtualhost
        /hst:root:
          jcr:primaryType: hst:mount
          hst:mountpoint: /hst:publishing/hst:sites/economic-action-plan
          hst:schemeagnostic: true
          publishing:gtm: /content/documents/economic-action-plan/administration/analytics/dev
    /hst:hst/hst:hosts/int/scot/mygov/economicactionplan:
      jcr:primaryType: hst:virtualhost
      /int:
        jcr:primaryType: hst:virtualhost
        /hst:root:
          jcr:primaryType: hst:mount
          hst:mountpoint: /hst:publishing/hst:sites/economic-action-plan
          hst:schemeagnostic: true
          publishing:gtm: /content/documents/economic-action-plan/administration/analytics/dev
    /hst:hst/hst:hosts/exp/scot/mygov/economicactionplan:
      jcr:primaryType: hst:virtualhost
      /exp:
        jcr:primaryType: hst:virtualhost
        /hst:root:
          jcr:primaryType: hst:mount
          hst:mountpoint: /hst:publishing/hst:sites/economic-action-plan
          hst:schemeagnostic: true
          publishing:gtm: /content/documents/economic-action-plan/administration/analytics/dev
    /hst:hst/hst:hosts/uat/scot/mygov/economicactionplan:
      jcr:primaryType: hst:virtualhost
      /uat:
        jcr:primaryType: hst:virtualhost
        /hst:root:
          jcr:primaryType: hst:mount
          hst:mountpoint: /hst:publishing/hst:sites/economic-action-plan
          hst:schemeagnostic: true
          publishing:gtm: /content/documents/economic-action-plan/administration/analytics/dev
    /hst:hst/hst:hosts/per/scot/mygov/economicactionplan:
      jcr:primaryType: hst:virtualhost
      /per:
        jcr:primaryType: hst:virtualhost
        /hst:root:
          jcr:primaryType: hst:mount
          hst:mountpoint: /hst:publishing/hst:sites/economic-action-plan
          hst:schemeagnostic: true
          publishing:gtm: /content/documents/economic-action-plan/administration/analytics/dev
    /hst:hst/hst:hosts/tst/scot/mygov/economicactionplan:
      jcr:primaryType: hst:virtualhost
      /tst:
        jcr:primaryType: hst:virtualhost
        /hst:root:
          jcr:primaryType: hst:mount
          hst:mountpoint: /hst:publishing/hst:sites/economic-action-plan
          hst:schemeagnostic: true
          publishing:gtm: /content/documents/economic-action-plan/administration/analytics/dev
    /hst:hst/hst:hosts/blu/scot/mygov/economicactionplan:
      jcr:primaryType: hst:virtualhost
      /blu:
        jcr:primaryType: hst:virtualhost
        /hst:root:
          jcr:primaryType: hst:mount
          hst:mountpoint: /hst:publishing/hst:sites/economic-action-plan
          hst:schemeagnostic: true
          publishing:gtm: /content/documents/economic-action-plan/administration/analytics/live
    /hst:hst/hst:hosts/grn/scot/mygov/economicactionplan:
      jcr:primaryType: hst:virtualhost
      /grn:
        jcr:primaryType: hst:virtualhost
        /hst:root:
          jcr:primaryType: hst:mount
          hst:mountpoint: /hst:publishing/hst:sites/economic-action-plan
          hst:schemeagnostic: true
          publishing:gtm: /content/documents/economic-action-plan/administration/analytics/live
    /hst:hst/hst:hosts/live/scot/mygov/economicactionplan:
      jcr:primaryType: hst:virtualhost
      /live:
        jcr:primaryType: hst:virtualhost
        /hst:root:
          jcr:primaryType: hst:mount
          hst:mountpoint: /hst:publishing/hst:sites/economic-action-plan
          hst:schemeagnostic: true
          publishing:gtm: /content/documents/economic-action-plan/administration/analytics/live
    /hst:hst/hst:hosts/origin/scot/mygov/economicactionplan:
      jcr:primaryType: hst:virtualhost
      /origin:
        jcr:primaryType: hst:virtualhost
        /hst:root:
          jcr:primaryType: hst:mount
          hst:mountpoint: /hst:publishing/hst:sites/economic-action-plan
          hst:schemeagnostic: true
          publishing:gtm: /content/documents/economic-action-plan/administration/analytics/live
    /hst:hst/hst:hosts/production/scot/mygov/economicactionplan:
      jcr:primaryType: hst:virtualhost
      /hst:root:
        jcr:primaryType: hst:mount
        hst:mountpoint: /hst:publishing/hst:sites/economic-action-plan
        hst:schemeagnostic: true
        publishing:gtm: /content/documents/economic-action-plan/administration/analytics/live
