definitions:
  config:
    /hst:hst/hst:hosts/dev-localhost/localhost/hst:root/mygov:
      .meta:residual-child-node-category: content
      jcr:primaryType: hst:mount
      hst:mountpoint: /hst:publishing/hst:sites/mygov
      hst:locale: en_GB
      publishing:gtm: /content/documents/mygov/administration/analytics/dev
      publishing:recaptcha: /content/documents/mygov/administration/recaptcha/dev
    /hst:hst/hst:hosts/dev-localhost/localhost/hst:root/mygov-preview:
      .meta:residual-child-node-category: content
      jcr:primaryType: hst:mount
      hst:alias: mygov-staging
      hst:mountpoint: /hst:publishing/hst:sites/mygov
      hst:type: preview
      preview-cookie-httponly: 'false'
      preview-cookie-secure: 'false'
      hst:locale: en_GB
    /hst:hst/hst:hosts/lcl/scot/mygov/www:
      jcr:primaryType: hst:virtualhost
      /lcl:
        jcr:primaryType: hst:virtualhost
        /hst:root:
          jcr:primaryType: hst:mount
          hst:mountpoint: /hst:publishing/hst:sites/mygov
          hst:schemeagnostic: true
          publishing:gtm: /content/documents/mygov/administration/analytics/dev
          publishing:recaptcha: /content/documents/mygov/administration/recaptcha/live
          hst:locale: en_GB
    /hst:hst/hst:hosts/lcl/scot/mygov/preview:
      jcr:primaryType: hst:virtualhost
      /lcl:
        jcr:primaryType: hst:virtualhost
        /hst:root:
          jcr:primaryType: hst:mount
          hst:alias: mygov-staging
          hst:mountpoint: /hst:publishing/hst:sites/mygov
          hst:schemeagnostic: true
          hst:type: preview
          preview-cookie-httponly: 'false'
          preview-cookie-secure: 'false'
          publishing:gtm: /content/documents/mygov/administration/analytics/dev
          publishing:recaptcha: /content/documents/mygov/administration/recaptcha/live
          hst:locale: en_GB
    /hst:hst/hst:hosts/dev/scot/mygov/www:
      jcr:primaryType: hst:virtualhost
      /dev:
        jcr:primaryType: hst:virtualhost
        /hst:root:
          jcr:primaryType: hst:mount
          hst:mountpoint: /hst:publishing/hst:sites/mygov
          hst:schemeagnostic: true
          publishing:gtm: /content/documents/mygov/administration/analytics/dev
          publishing:recaptcha: /content/documents/mygov/administration/recaptcha/live
          hst:locale: en_GB
    /hst:hst/hst:hosts/dev/scot/mygov/preview:
      jcr:primaryType: hst:virtualhost
      /dev:
        jcr:primaryType: hst:virtualhost
        /hst:root:
          jcr:primaryType: hst:mount
          hst:alias: mygov-staging
          hst:mountpoint: /hst:publishing/hst:sites/mygov
          hst:schemeagnostic: true
          hst:type: preview
          preview-cookie-httponly: 'false'
          preview-cookie-secure: 'false'
          publishing:gtm: /content/documents/mygov/administration/analytics/dev
          publishing:recaptcha: /content/documents/mygov/administration/recaptcha/live
          hst:locale: en_GB
    /hst:hst/hst:hosts/int/scot/mygov/www:
      jcr:primaryType: hst:virtualhost
      /int:
        jcr:primaryType: hst:virtualhost
        /hst:root:
          jcr:primaryType: hst:mount
          hst:mountpoint: /hst:publishing/hst:sites/mygov
          hst:schemeagnostic: true
          publishing:gtm: /content/documents/mygov/administration/analytics/dev
          publishing:recaptcha: /content/documents/mygov/administration/recaptcha/dev
          hst:locale: en_GB
    /hst:hst/hst:hosts/int/scot/mygov/preview:
      jcr:primaryType: hst:virtualhost
      /int:
        jcr:primaryType: hst:virtualhost
        /hst:root:
          jcr:primaryType: hst:mount
          hst:alias: mygov-staging
          hst:mountpoint: /hst:publishing/hst:sites/mygov
          hst:schemeagnostic: true
          hst:type: preview
          preview-cookie-httponly: 'false'
          preview-cookie-secure: 'false'
          publishing:gtm: /content/documents/mygov/administration/analytics/dev
          publishing:recaptcha: /content/documents/mygov/administration/recaptcha/dev
          hst:locale: en_GB
    /hst:hst/hst:hosts/exp/scot/mygov/www:
      jcr:primaryType: hst:virtualhost
      /exp:
        jcr:primaryType: hst:virtualhost
        /hst:root:
          jcr:primaryType: hst:mount
          hst:mountpoint: /hst:publishing/hst:sites/mygov
          hst:schemeagnostic: true
          publishing:gtm: /content/documents/mygov/administration/analytics/dev
          publishing:recaptcha: /content/documents/mygov/administration/recaptcha/live
          hst:locale: en_GB
    /hst:hst/hst:hosts/exp/scot/mygov/preview:
      jcr:primaryType: hst:virtualhost
      /exp:
        jcr:primaryType: hst:virtualhost
        /hst:root:
          jcr:primaryType: hst:mount
          hst:alias: mygov-staging
          hst:mountpoint: /hst:publishing/hst:sites/mygov
          hst:schemeagnostic: true
          hst:type: preview
          preview-cookie-httponly: 'false'
          preview-cookie-secure: 'false'
          publishing:gtm: /content/documents/mygov/administration/analytics/dev
          publishing:recaptcha: /content/documents/mygov/administration/recaptcha/live
          hst:locale: en_GB
    /hst:hst/hst:hosts/uat/scot/mygov/www:
      jcr:primaryType: hst:virtualhost
      /uat:
        jcr:primaryType: hst:virtualhost
        /hst:root:
          jcr:primaryType: hst:mount
          hst:mountpoint: /hst:publishing/hst:sites/mygov
          hst:schemeagnostic: true
          publishing:gtm: /content/documents/mygov/administration/analytics/dev
          publishing:recaptcha: /content/documents/mygov/administration/recaptcha/live
          hst:locale: en_GB
    /hst:hst/hst:hosts/uat/scot/mygov/preview:
      jcr:primaryType: hst:virtualhost
      /uat:
        jcr:primaryType: hst:virtualhost
        /hst:root:
          jcr:primaryType: hst:mount
          hst:alias: mygov-staging
          hst:mountpoint: /hst:publishing/hst:sites/mygov
          hst:schemeagnostic: true
          hst:type: preview
          preview-cookie-httponly: 'false'
          preview-cookie-secure: 'false'
          publishing:gtm: /content/documents/mygov/administration/analytics/dev
          publishing:recaptcha: /content/documents/mygov/administration/recaptcha/live
          hst:locale: en_GB
    /hst:hst/hst:hosts/per/scot/mygov/www:
      jcr:primaryType: hst:virtualhost
      /per:
        jcr:primaryType: hst:virtualhost
        /hst:root:
          jcr:primaryType: hst:mount
          hst:mountpoint: /hst:publishing/hst:sites/mygov
          hst:schemeagnostic: true
          publishing:gtm: /content/documents/mygov/administration/analytics/dev
          publishing:recaptcha: /content/documents/mygov/administration/recaptcha/dev
          hst:locale: en_GB
    /hst:hst/hst:hosts/per/scot/mygov/preview:
      jcr:primaryType: hst:virtualhost
      /per:
        jcr:primaryType: hst:virtualhost
        /hst:root:
          jcr:primaryType: hst:mount
          hst:alias: mygov-staging
          hst:mountpoint: /hst:publishing/hst:sites/mygov
          hst:schemeagnostic: true
          hst:type: preview
          preview-cookie-httponly: 'false'
          preview-cookie-secure: 'false'
          publishing:gtm: /content/documents/mygov/administration/analytics/dev
          publishing:recaptcha: /content/documents/mygov/administration/recaptcha/dev
          hst:locale: en_GB
    /hst:hst/hst:hosts/tst/scot/mygov/www:
      jcr:primaryType: hst:virtualhost
      /tst:
        jcr:primaryType: hst:virtualhost
        /hst:root:
          jcr:primaryType: hst:mount
          hst:mountpoint: /hst:publishing/hst:sites/mygov
          hst:schemeagnostic: true
          publishing:gtm: /content/documents/mygov/administration/analytics/dev
          publishing:recaptcha: /content/documents/mygov/administration/recaptcha/live
          hst:locale: en_GB
    /hst:hst/hst:hosts/tst/scot/mygov/preview:
      jcr:primaryType: hst:virtualhost
      /tst:
        jcr:primaryType: hst:virtualhost
        /hst:root:
          jcr:primaryType: hst:mount
          hst:alias: mygov-staging
          hst:mountpoint: /hst:publishing/hst:sites/mygov
          hst:schemeagnostic: true
          hst:type: preview
          preview-cookie-httponly: 'false'
          preview-cookie-secure: 'false'
          publishing:gtm: /content/documents/mygov/administration/analytics/dev
          publishing:recaptcha: /content/documents/mygov/administration/recaptcha/live
          hst:locale: en_GB
    /hst:hst/hst:hosts/blu/scot/mygov/www:
      jcr:primaryType: hst:virtualhost
      /blu:
        jcr:primaryType: hst:virtualhost
        /hst:root:
          jcr:primaryType: hst:mount
          hst:mountpoint: /hst:publishing/hst:sites/mygov
          hst:schemeagnostic: true
          publishing:gtm: /content/documents/mygov/administration/analytics/live
          publishing:recaptcha: /content/documents/mygov/administration/recaptcha/live
          hst:locale: en_GB
    /hst:hst/hst:hosts/blu/scot/mygov/preview:
      jcr:primaryType: hst:virtualhost
      /blu:
        .meta:residual-child-node-category: content
        jcr:primaryType: hst:virtualhost
        /hst:root:
          .meta:residual-child-node-category: content
          jcr:primaryType: hst:mount
          hst:alias: mygov-staging
          hst:mountpoint: /hst:publishing/hst:sites/mygov
          hst:schemeagnostic: true
          hst:type: preview
          preview-cookie-httponly: 'false'
          preview-cookie-secure: 'false'
          publishing:gtm: /content/documents/mygov/administration/analytics/live
          publishing:recaptcha: /content/documents/mygov/administration/recaptcha/live
          hst:locale: en_GB
    /hst:hst/hst:hosts/grn/scot/mygov/www:
      jcr:primaryType: hst:virtualhost
      /grn:
        jcr:primaryType: hst:virtualhost
        /hst:root:
          jcr:primaryType: hst:mount
          hst:mountpoint: /hst:publishing/hst:sites/mygov
          hst:schemeagnostic: true
          publishing:gtm: /content/documents/mygov/administration/analytics/live
          publishing:recaptcha: /content/documents/mygov/administration/recaptcha/live
          hst:locale: en_GB
    /hst:hst/hst:hosts/grn/scot/mygov/preview:
      jcr:primaryType: hst:virtualhost
      /grn:
        jcr:primaryType: hst:virtualhost
        /hst:root:
          jcr:primaryType: hst:mount
          hst:alias: mygov-staging
          hst:mountpoint: /hst:publishing/hst:sites/mygov
          hst:schemeagnostic: true
          hst:type: preview
          preview-cookie-httponly: 'false'
          preview-cookie-secure: 'false'
          publishing:gtm: /content/documents/mygov/administration/analytics/live
          publishing:recaptcha: /content/documents/mygov/administration/recaptcha/live
          hst:locale: en_GB
    /hst:hst/hst:hosts/live/scot/mygov/www:
      jcr:primaryType: hst:virtualhost
      /live:
        jcr:primaryType: hst:virtualhost
        /hst:root:
          jcr:primaryType: hst:mount
          hst:mountpoint: /hst:publishing/hst:sites/mygov
          hst:schemeagnostic: true
          publishing:gtm: /content/documents/mygov/administration/analytics/live
          publishing:recaptcha: /content/documents/mygov/administration/recaptcha/live
          hst:locale: en_GB
    /hst:hst/hst:hosts/live/scot/mygov/preview:
      jcr:primaryType: hst:virtualhost
      /live:
        jcr:primaryType: hst:virtualhost
        /hst:root:
          jcr:primaryType: hst:mount
          hst:alias: mygov-staging
          hst:mountpoint: /hst:publishing/hst:sites/mygov
          hst:schemeagnostic: true
          hst:type: preview
          preview-cookie-httponly: 'false'
          preview-cookie-secure: 'false'
          publishing:gtm: /content/documents/mygov/administration/analytics/live
          publishing:recaptcha: /content/documents/mygov/administration/recaptcha/live
          hst:locale: en_GB
    /hst:hst/hst:hosts/origin/scot/mygov/www:
      jcr:primaryType: hst:virtualhost
      /origin:
        jcr:primaryType: hst:virtualhost
        /hst:root:
          jcr:primaryType: hst:mount
          hst:mountpoint: /hst:publishing/hst:sites/mygov
          hst:schemeagnostic: true
          publishing:gtm: /content/documents/mygov/administration/analytics/live
          publishing:recaptcha: /content/documents/mygov/administration/recaptcha/live
          hst:locale: en_GB
    /hst:hst/hst:hosts/origin/scot/mygov/preview:
      jcr:primaryType: hst:virtualhost
      /origin:
        jcr:primaryType: hst:virtualhost
        /hst:root:
          jcr:primaryType: hst:mount
          hst:alias: mygov-staging
          hst:mountpoint: /hst:publishing/hst:sites/mygov
          hst:schemeagnostic: true
          hst:type: preview
          preview-cookie-httponly: 'false'
          preview-cookie-secure: 'false'
          publishing:gtm: /content/documents/mygov/administration/analytics/live
          publishing:recaptcha: /content/documents/mygov/administration/recaptcha/live
          hst:locale: en_GB
    /hst:hst/hst:hosts/production/scot/mygov/www:
      jcr:primaryType: hst:virtualhost
      /hst:root:
        jcr:primaryType: hst:mount
        hst:mountpoint: /hst:publishing/hst:sites/mygov
        hst:schemeagnostic: true
        publishing:gtm: /content/documents/mygov/administration/analytics/live
        publishing:recaptcha: /content/documents/mygov/administration/recaptcha/live
        hst:locale: en_GB
    /hst:hst/hst:hosts/production/scot/mygov/preview:
      jcr:primaryType: hst:virtualhost
      /hst:root:
        jcr:primaryType: hst:mount
        hst:alias: mygov-staging
        hst:mountpoint: /hst:publishing/hst:sites/mygov
        hst:schemeagnostic: true
        hst:type: preview
        preview-cookie-httponly: 'false'
        preview-cookie-secure: 'false'
        publishing:gtm: /content/documents/mygov/administration/analytics/live
        publishing:recaptcha: /content/documents/mygov/administration/recaptcha/live
        hst:locale: en_GB
