definitions:
  config:
    /hst:hst/hst:hosts/dev-localhost/localhost/hst:root/trading-nation:
        .meta:residual-child-node-category: content
        jcr:primaryType: hst:mount
        hst:mountpoint: /hst:publishing/hst:sites/trading-nation
    /hst:hst/hst:hosts/lcl/scot/mygov/tradingnation:
        jcr:primaryType: hst:virtualhost
        /lcl:
          jcr:primaryType: hst:virtualhost
          /hst:root:
            jcr:primaryType: hst:mount
            hst:mountpoint: /hst:publishing/hst:sites/trading-nation
            hst:schemeagnostic: true
            publishing:gtm: /content/documents/trading-nation/administration/analytics/dev
    /hst:hst/hst:hosts/dev/scot/mygov/tradingnation:
        jcr:primaryType: hst:virtualhost
        /dev:
          jcr:primaryType: hst:virtualhost
          /hst:root:
            jcr:primaryType: hst:mount
            hst:mountpoint: /hst:publishing/hst:sites/trading-nation
            hst:schemeagnostic: true
            publishing:gtm: /content/documents/trading-nation/administration/analytics/dev
    /hst:hst/hst:hosts/int/scot/mygov/tradingnation:
        jcr:primaryType: hst:virtualhost
        /int:
          jcr:primaryType: hst:virtualhost
          /hst:root:
            jcr:primaryType: hst:mount
            hst:mountpoint: /hst:publishing/hst:sites/trading-nation
            hst:schemeagnostic: true
            publishing:gtm: /content/documents/trading-nation/administration/analytics/dev
    /hst:hst/hst:hosts/exp/scot/mygov/tradingnation:
        jcr:primaryType: hst:virtualhost
        /exp:
          jcr:primaryType: hst:virtualhost
          /hst:root:
            jcr:primaryType: hst:mount
            hst:mountpoint: /hst:publishing/hst:sites/trading-nation
            hst:schemeagnostic: true
            publishing:gtm: /content/documents/trading-nation/administration/analytics/dev
    /hst:hst/hst:hosts/uat/scot/mygov/tradingnation:
        jcr:primaryType: hst:virtualhost
        /uat:
          jcr:primaryType: hst:virtualhost
          /hst:root:
            jcr:primaryType: hst:mount
            hst:mountpoint: /hst:publishing/hst:sites/trading-nation
            hst:schemeagnostic: true
            publishing:gtm: /content/documents/trading-nation/administration/analytics/dev
    /hst:hst/hst:hosts/per/scot/mygov/tradingnation:
        jcr:primaryType: hst:virtualhost
        /per:
          jcr:primaryType: hst:virtualhost
          /hst:root:
            jcr:primaryType: hst:mount
            hst:mountpoint: /hst:publishing/hst:sites/trading-nation
            hst:schemeagnostic: true
            publishing:gtm: /content/documents/trading-nation/administration/analytics/dev
    /hst:hst/hst:hosts/tst/scot/mygov/tradingnation:
        jcr:primaryType: hst:virtualhost
        /tst:
          jcr:primaryType: hst:virtualhost
          /hst:root:
            jcr:primaryType: hst:mount
            hst:mountpoint: /hst:publishing/hst:sites/trading-nation
            hst:schemeagnostic: true
            publishing:gtm: /content/documents/trading-nation/administration/analytics/dev
    /hst:hst/hst:hosts/blu/scot/mygov/tradingnation:
        jcr:primaryType: hst:virtualhost
        /blu:
          jcr:primaryType: hst:virtualhost
          /hst:root:
            jcr:primaryType: hst:mount
            hst:mountpoint: /hst:publishing/hst:sites/trading-nation
            hst:schemeagnostic: true
            publishing:gtm: /content/documents/trading-nation/administration/analytics/live
    /hst:hst/hst:hosts/grn/scot/mygov/tradingnation:
        jcr:primaryType: hst:virtualhost
        /grn:
          jcr:primaryType: hst:virtualhost
          /hst:root:
            jcr:primaryType: hst:mount
            hst:mountpoint: /hst:publishing/hst:sites/trading-nation
            hst:schemeagnostic: true
            publishing:gtm: /content/documents/trading-nation/administration/analytics/live
    /hst:hst/hst:hosts/live/scot/mygov/tradingnation:
        jcr:primaryType: hst:virtualhost
        /live:
          jcr:primaryType: hst:virtualhost
          /hst:root:
            jcr:primaryType: hst:mount
            hst:mountpoint: /hst:publishing/hst:sites/trading-nation
            hst:schemeagnostic: true
            publishing:gtm: /content/documents/trading-nation/administration/analytics/live
    /hst:hst/hst:hosts/origin/scot/mygov/tradingnation:
        jcr:primaryType: hst:virtualhost
        /origin:
          jcr:primaryType: hst:virtualhost
          /hst:root:
            jcr:primaryType: hst:mount
            hst:mountpoint: /hst:publishing/hst:sites/trading-nation
            hst:schemeagnostic: true
            publishing:gtm: /content/documents/trading-nation/administration/analytics/live
    /hst:hst/hst:hosts/production/scot/mygov/tradingnation:
        jcr:primaryType: hst:virtualhost
        /hst:root:
          jcr:primaryType: hst:mount
          hst:mountpoint: /hst:publishing/hst:sites/trading-nation
          hst:schemeagnostic: true
          publishing:gtm: /content/documents/trading-nation/administration/analytics/live
