definitions:
  config:
    /hst:hst/hst:configurations/common/hst:abstractpages/base:
      jcr:primaryType: hst:component
      hst:template: base-layout
      hst:componentclassname: scot.mygov.publishing.components.DetermineStylingComponent
      /notifications:
        jcr:primaryType: hst:component
        hst:template: base-notifications
        hst:componentclassname: scot.mygov.publishing.components.NotificationBannersComponent
      /siteheader:
        jcr:primaryType: hst:component
        hst:template: base-siteheader
        hst:componentclassname: scot.mygov.publishing.components.SiteHeaderComponent
        /menu:
          jcr:primaryType: hst:component
          hst:componentclassname: org.onehippo.cms7.essentials.components.EssentialsMenuComponent
          hst:parameternames: [selectedMenu, level, menu]
          hst:parametervalues: ['on', '1', main]
          hst:template: site-navigation
        /mobilemenu:
          jcr:primaryType: hst:component
          hst:componentclassname: org.onehippo.cms7.essentials.components.EssentialsMenuComponent
          hst:parameternames: [selectedMenu, level, menu]
          hst:parametervalues: ['on', '1', main]
          hst:template: site-navigation-mobile
        /search-bar:
          jcr:primaryType: hst:component
          hst:componentclassname: scot.mygov.publishing.components.SearchBarComponent
          hst:template: search-bar
      /footer:
        jcr:primaryType: hst:component
        hst:componentclassname: scot.mygov.publishing.components.FooterComponent
        hst:parameternames: [path]
        hst:parametervalues: [site-furniture/footer]
        hst:template: base-footer
      /googletagmanager:
        jcr:primaryType: hst:component
        hst:template: base-googletagmanager
        hst:componentclassname: scot.mygov.publishing.components.GoogleTagManagerComponent
      /plausibleanalytics:
        jcr:primaryType: hst:component
        hst:componentclassname: scot.mygov.publishing.components.PlausibleAnalyticsComponent
        hst:template: base-plausibleanalytics
      /preview-indicator:
        jcr:primaryType: hst:component
        hst:componentclassname: scot.gov.publishing.staging.components.PreviewIndicatorComponent
        hst:template: preview-indicator
      /seo:
        jcr:primaryType: hst:component
        hst:componentclassname: scot.mygov.publishing.components.SEOComponent
        hst:template: seo
