definitions:
  config:
    /hst:hst/hst:configurations/common/hst:abstractpages/base:
      jcr:primaryType: hst:component
      hst:template: base-layout
      hst:componentclassname: scot.mygov.publishing.components.DetermineStylingComponent
      /notifications:
        jcr:primaryType: hst:component
        hst:template: base-notifications
        hst:componentclassname: scot.mygov.publishing.components.NotificationBannersComponent
      /siteheader:
        jcr:primaryType: hst:component
        hst:template: base-siteheader
        hst:componentclassname: scot.mygov.publishing.components.SiteHeaderComponent
      /footer:
        jcr:primaryType: hst:component
        hst:componentclassname: scot.mygov.publishing.components.FooterComponent
        hst:parameternames: [path]
        hst:parametervalues: [site-furniture/footer]
        hst:template: base-footer
      /googletagmanager:
        jcr:primaryType: hst:component
        hst:template: base-googletagmanager
        hst:componentclassname: scot.mygov.publishing.components.GoogleTagManagerComponent
      /preview-indicator:
        jcr:primaryType: hst:component
        hst:componentclassname: scot.mygov.publishing.components.PreviewIndicatorComponent
        hst:template: preview-indicator
      /seo:
        jcr:primaryType: hst:component
        hst:componentclassname: scot.mygov.publishing.components.SEOComponent
        hst:template: seo
        hst:parameternames: [showTitle]
        hst:parametervalues: ['false']
