definitions:
  config:
    /hippo:configuration/hippo:workflows/default/handle/frontend:renderer/preview:
      jcr:primaryType: frontend:plugin
      plugin.class: scot.mygov.publishing.plugins.PreviewPlugin
      wicket.id: ${item}
      invalidation.time.days: 30
