definitions:
  config:
    /hippo:configuration/hippo:workflows/default/handle/frontend:renderer/preview:
      jcr:primaryType: frontend:plugin
      plugin.class: scot.gov.publishing.staging.plugins.PreviewPlugin
      wicket.id: ${item}
