definitions:
  config:
    /hst:hst/hst:hosts:
      /dev-localhost:
        .meta:residual-child-node-category: content
        jcr:primaryType: hst:virtualhostgroup
        hst:defaultport: 8080
        /localhost:
          .meta:residual-child-node-category: content
          jcr:primaryType: hst:virtualhost
          /hst:root:
            .meta:residual-child-node-category: content
            jcr:primaryType: hst:mount
            hst:homepage: root
            hst:mountpoint: /hst:publishing/hst:sites/publishing
            hst:nochannelinfo: true
      /lcl:
        jcr:primaryType: hst:virtualhostgroup
        /scot:
          jcr:primaryType: hst:virtualhost
          hst:scheme: https
          hst:showcontextpath: false
          hst:showport: false
          /mygov:
            jcr:primaryType: hst:virtualhost
          /gov:
            jcr:primaryType: hst:virtualhost
            /jobs:
              jcr:primaryType: hst:virtualhost
              /digital:
                jcr:primaryType: hst:virtualhost
      /dev:
        jcr:primaryType: hst:virtualhostgroup
        /scot:
          jcr:primaryType: hst:virtualhost
          hst:scheme: https
          hst:showcontextpath: false
          hst:showport: false
          /mygov:
            jcr:primaryType: hst:virtualhost
          /gov:
            jcr:primaryType: hst:virtualhost
            /jobs:
                jcr:primaryType: hst:virtualhost
                /digital:
                  jcr:primaryType: hst:virtualhost
      /int:
        jcr:primaryType: hst:virtualhostgroup
        /scot:
          jcr:primaryType: hst:virtualhost
          hst:scheme: https
          hst:showcontextpath: false
          hst:showport: false
          /mygov:
            jcr:primaryType: hst:virtualhost
          /gov:
            jcr:primaryType: hst:virtualhost
            /jobs:
                jcr:primaryType: hst:virtualhost
                /digital:
                  jcr:primaryType: hst:virtualhost
      /exp:
        jcr:primaryType: hst:virtualhostgroup
        /scot:
          jcr:primaryType: hst:virtualhost
          hst:scheme: https
          hst:showcontextpath: false
          hst:showport: false
          /mygov:
            jcr:primaryType: hst:virtualhost
          /gov:
            jcr:primaryType: hst:virtualhost
            /jobs:
              jcr:primaryType: hst:virtualhost
              /digital:
                jcr:primaryType: hst:virtualhost
      /uat:
        jcr:primaryType: hst:virtualhostgroup
        /scot:
          jcr:primaryType: hst:virtualhost
          hst:scheme: https
          hst:showcontextpath: false
          hst:showport: false
          /mygov:
            jcr:primaryType: hst:virtualhost
          /gov:
            jcr:primaryType: hst:virtualhost
            /jobs:
              jcr:primaryType: hst:virtualhost
              /digital:
                jcr:primaryType: hst:virtualhost
      /per:
        jcr:primaryType: hst:virtualhostgroup
        /scot:
          jcr:primaryType: hst:virtualhost
          hst:scheme: https
          hst:showcontextpath: false
          hst:showport: false
          /mygov:
            jcr:primaryType: hst:virtualhost
          /gov:
            jcr:primaryType: hst:virtualhost
            /jobs:
              jcr:primaryType: hst:virtualhost
              /digital:
                jcr:primaryType: hst:virtualhost
      /tst:
        jcr:primaryType: hst:virtualhostgroup
        /scot:
          jcr:primaryType: hst:virtualhost
          hst:scheme: https
          hst:showcontextpath: false
          hst:showport: false
          /mygov:
            jcr:primaryType: hst:virtualhost
          /gov:
            jcr:primaryType: hst:virtualhost
            /jobs:
              jcr:primaryType: hst:virtualhost
              /digital:
                jcr:primaryType: hst:virtualhost
      /blu:
        jcr:primaryType: hst:virtualhostgroup
        /scot:
          jcr:primaryType: hst:virtualhost
          hst:scheme: https
          hst:showcontextpath: false
          hst:showport: false
          /mygov:
            jcr:primaryType: hst:virtualhost
          /gov:
            jcr:primaryType: hst:virtualhost
            /jobs:
              jcr:primaryType: hst:virtualhost
              /digital:
                jcr:primaryType: hst:virtualhost
      /grn:
        jcr:primaryType: hst:virtualhostgroup
        /scot:
          jcr:primaryType: hst:virtualhost
          hst:scheme: https
          hst:showcontextpath: false
          hst:showport: false
          /mygov:
            jcr:primaryType: hst:virtualhost
          /gov:
            jcr:primaryType: hst:virtualhost
            /jobs:
              jcr:primaryType: hst:virtualhost
              /digital:
                jcr:primaryType: hst:virtualhost
      /live:
        jcr:primaryType: hst:virtualhostgroup
        /scot:
          jcr:primaryType: hst:virtualhost
          hst:scheme: https
          hst:showcontextpath: false
          hst:showport: false
          /mygov:
            jcr:primaryType: hst:virtualhost
          /gov:
            jcr:primaryType: hst:virtualhost
            /jobs:
              jcr:primaryType: hst:virtualhost
              /digital:
                jcr:primaryType: hst:virtualhost
      /origin:
        jcr:primaryType: hst:virtualhostgroup
        /scot:
          jcr:primaryType: hst:virtualhost
          hst:scheme: https
          hst:showcontextpath: false
          hst:showport: false
          /mygov:
            jcr:primaryType: hst:virtualhost
          /gov:
            jcr:primaryType: hst:virtualhost
            /jobs:
              jcr:primaryType: hst:virtualhost
              /digital:
                jcr:primaryType: hst:virtualhost
      /production:
        jcr:primaryType: hst:virtualhostgroup
        /scot:
          jcr:primaryType: hst:virtualhost
          hst:scheme: https
          hst:showcontextpath: false
          hst:showport: false
          /mygov:
            jcr:primaryType: hst:virtualhost
          /gov:
            jcr:primaryType: hst:virtualhost
            /jobs:
              jcr:primaryType: hst:virtualhost
              /digital:
                jcr:primaryType: hst:virtualhost