definitions:
  config:
    /hippo:configuration/hippo:modules/webfiles/hippo:moduleconfig:
      watchedModules: [repository-data/webfiles]
      maxFileLengthKb: 790
    /hippo:configuration/hippo:domains/preview-documents/readonly:
      hipposys:groups:
        operation: add
        type: string
        value: [previewusers]
    /hippo:configuration/hippo:domains/live-documents/readonly:
      hipposys:groups:
        operation: add
        type: string
        value: [liveusers]
