#!/bin/sh
set -eu

restart_flag=/opt/hippo/temp/.restart

if [ "$1" = triggered ]; then
  if [ -f "$restart_flag" ]; then
    rm "$restart_flag"
    if systemctl is-enabled --quiet hippo 2>/dev/null; then
      systemctl restart hippo
    fi
  fi
fi
