package scot.mygov.publishing.validation;

import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;
import org.jsoup.select.Elements;
import org.onehippo.cms.services.validation.api.ValidationContext;
import org.onehippo.cms.services.validation.api.Validator;
import org.onehippo.cms.services.validation.api.Violation;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.jcr.Node;
import javax.jcr.RepositoryException;
import java.util.Optional;

/**
 * Validates that HTML fields do not contain any links with a preview_token query parameter.
 * Such links are generated by the CMS preview feature and should never be persisted in content.
 *
 * Applied to fields of type hippostd:html, which are JCR nodes — the HTML content is read
 * from the hippostd:content property of the node.
 */
public class PreviewTokenValidator implements Validator<Node> {

    private static final Logger LOG = LoggerFactory.getLogger(PreviewTokenValidator.class);

    static final String PREVIEW_TOKEN_PARAM = "preview_token";

    static final String CONTENT_PROPERTY = "hippostd:content";

    @Override
    public Optional<Violation> validate(ValidationContext context, Node node) {
        LOG.debug("PreviewTokenValidator running for node type {}", context.getJcrType());
        try {
            if (!node.hasProperty(CONTENT_PROPERTY)) {
                LOG.debug("PreviewTokenValidator: no {} property found, skipping", CONTENT_PROPERTY);
                return Optional.empty();
            }
            String html = node.getProperty(CONTENT_PROPERTY).getString();
            Optional<Violation> result = validateHtml(context, html);
            if (result.isPresent()) {
                LOG.warn("PreviewTokenValidator: preview_token link found in {} field", context.getJcrName());
            }
            return result;
        } catch (RepositoryException e) {
            LOG.error("Failed to read HTML content during preview_token validation", e);
            return Optional.empty();
        }
    }

    Optional<Violation> validateHtml(ValidationContext context, String html) {
        if (html == null || html.isEmpty()) {
            return Optional.empty();
        }
        Document document = Jsoup.parse(html);
        Elements links = document.select("a[href]");
        for (Element link : links) {
            if (containsPreviewToken(link.attr("href"))) {
                return Optional.of(context.createViolation());
            }
        }
        return Optional.empty();
    }

    boolean containsPreviewToken(String href) {
        if (href == null) {
            return false;
        }
        int queryStart = href.indexOf('?');
        if (queryStart < 0) {
            return false;
        }
        String query = href.substring(queryStart + 1);
        for (String param : query.split("&")) {
            String name = param.contains("=") ? param.substring(0, param.indexOf('=')) : param;
            if (PREVIEW_TOKEN_PARAM.equals(name)) {
                return true;
            }
        }
        return false;
    }
}
