definitions:
  config:
    /hst:hst/hst:configurations/mygov/hst:abstractpages/base:
      jcr:primaryType: hst:component
      hst:componentclassname: scot.mygov.publishing.components.DetermineStylingComponent
      hst:template: base-layout
      /notifications:
        jcr:primaryType: hst:component
        hst:componentclassname: scot.mygov.publishing.components.NotificationBannersComponent
        hst:template: base-notifications
      /siteheader:
        jcr:primaryType: hst:component
        hst:template: mygov-siteheader
      /footer:
        jcr:primaryType: hst:component
        hst:componentclassname: scot.mygov.publishing.components.FooterComponent
        hst:parameternames: [path]
        hst:parametervalues: [site-furniture/footer]
        hst:template: base-footer
      /googletagmanager:
        jcr:primaryType: hst:component
        hst:componentclassname: scot.mygov.publishing.components.GoogleTagManagerComponent
        hst:template: base-googletagmanager